import PageHeader from "@/components/docs/PageHeader";
import CodeBlock from "@/components/docs/CodeBlock";

const llmBlock = `# NexArt Apps
Apps are organizational units within a Project.

## Hierarchy
Project → Apps → CER records

Apps represent the specific application, service, or workflow that produced the attestation.
They are used for organization and filtering. They do not change the cryptographic structure of CERs.

## In CER metadata
{ "metadata": { "appId": "customer-chatbot" } }
This associates the record with the correct app in the dashboard.

## Dashboard capabilities
- Filter CER records by app
- View attestations per service
- Export records scoped to an app

## Benefits
- Separate CERs by application or microservice
- App identifiers included in audit exports
- Track which services generate attestations`;

const Apps = () => (
  <>
    <PageHeader
      title="Apps"
      summary="Organizational units within a project for grouping CER records by application or service."
      llmBlock={llmBlock}
    />

    <h2 id="overview">Overview</h2>
    <p>Apps are organizational units within a Project. They represent the specific application, service, or workflow that produced an attestation.</p>
    <ul>
      <li><strong>Project</strong>
        <ul>
          <li><strong>Apps</strong>
            <ul>
              <li><strong>CER records</strong></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
    <p>Apps are used for organization and filtering. They do not change the cryptographic structure of CERs.</p>

    <h2 id="why">Why Use Apps</h2>
    <ul>
      <li><strong>Organization.</strong> Separate CER records by application or microservice.</li>
      <li><strong>Filtering.</strong> Filter the dashboard view to show attestations for a specific app.</li>
      <li><strong>Audit Context.</strong> App identifiers are included in CER metadata and audit exports, helping auditors understand which system produced the execution.</li>
      <li><strong>Operational Visibility.</strong> Track which services generate attestations and monitor activity per app.</li>
    </ul>

    <h2 id="create">Creating an App</h2>
    <ol>
      <li>Open the NexArt Dashboard</li>
      <li>Navigate to <strong>Projects</strong></li>
      <li>Select the project where the app should belong</li>
      <li>Open the <strong>Apps</strong> tab</li>
      <li>Click <strong>Add App</strong></li>
      <li>Enter an app name</li>
    </ol>
    <p>Examples of app names:</p>
    <ul>
      <li>customer-chatbot</li>
      <li>document-summarizer</li>
      <li>fraud-detector</li>
      <li>support-assistant</li>
    </ul>

    <h2 id="in-attestations">Using Apps in Attestations</h2>
    <p>When creating a CER, the app identifier may be included in the snapshot metadata:</p>
    <CodeBlock
      code={`{
  "snapshot": {
    "metadata": {
      "appId": "customer-chatbot",
      "projectId": "proj_abc123"
    }
  }
}`}
      title="App identifier in CER metadata"
    />
    <p>This allows NexArt to associate the record with the correct application in the dashboard. The association is used for dashboard organization and exports.</p>

    <h2 id="dashboard">Apps in the Dashboard</h2>
    <p>In the dashboard, apps let you:</p>
    <ul>
      <li>Filter CER records by app</li>
      <li>View attestations generated by a specific service</li>
      <li>Export records scoped to an app</li>
    </ul>
  </>
);

export default Apps;
