import PageHeader from "@/components/docs/PageHeader";
import CodeBlock from "@/components/docs/CodeBlock";

const llmBlock = `# NexArt Signed Receipts
A signed receipt is the attestation artifact returned by a node after it attests a CER.

## What it proves
- The node witnessed the CER bundle
- The receipt binds the node's identity and timestamp to the CER's certificateHash
- The signature is Ed25519

## Receipt structure
{
  receipt: {
    certificateHash: "sha256:...",   // SHA-256 hash of the CER bundle
    timestamp: ISO 8601,              // attestation time from the node
    nodeId: "...",                     // node that produced the receipt
    attestorKeyId: "..."              // signing key used
  },
  signature: <raw Ed25519 bytes>,
  signatureB64Url: <base64url-encoded signature>
}

## Verification
1. Fetch node keys from node.nexart.io/.well-known/nexart-node.json
2. Select the key matching attestorKeyId
3. Verify Ed25519 signature over the canonical receipt payload
4. Confirm receipt's certificateHash matches the CER bundle

Or verify through verify.nexart.io.

## Key discovery
node.nexart.io/.well-known/nexart-node.json
Fields: nodeId, activeKid, keys[] (kid, algorithm, publicKey)`;

const SignedReceipts = () => (
  <>
    <PageHeader
      title="Signed Receipts"
      summary="The attestation artifact returned by a node after it attests a CER."
      llmBlock={llmBlock}
    />

    <h2 id="what">What is a Signed Receipt?</h2>
    <p>A signed receipt is the attestation artifact returned by a node after it attests a CER bundle. It contains a canonical receipt payload plus a cryptographic signature.</p>
    <p>The receipt binds the CER's <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">certificateHash</code> to the node's identity and a timestamp. The signature proves the node witnessed the record — it does not imply the node stores or owns the execution data. Signatures use <strong>Ed25519</strong>.</p>

    <h2 id="shape">Receipt Structure</h2>
    <p>The <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">receipt</code> object is the canonical payload that is signed. Verification is performed against this payload.</p>
    <CodeBlock
      code={`{
  "receipt": {
    "certificateHash": "sha256:9e8d7c6b5a4f...",
    "timestamp": "2026-03-06T12:00:00.000Z",
    "nodeId": "nexart-node-primary",
    "attestorKeyId": "key_01HXYZ..."
  },
  "signature": "<raw Ed25519 signature bytes>",
  "signatureB64Url": "MEUCIQD3..."
}`}
      title="Signed Receipt"
    />

    <h2 id="fields">Field Reference</h2>
    <ul>
      <li><strong>receipt</strong> — The canonical payload signed by the node</li>
      <li><strong>certificateHash</strong> — SHA-256 hash of the CER bundle being attested</li>
      <li><strong>timestamp</strong> — Attestation time generated by the node</li>
      <li><strong>nodeId</strong> — Identifier of the node that produced the receipt</li>
      <li><strong>attestorKeyId</strong> — Identifies the node signing key used for this receipt</li>
      <li><strong>signature</strong> — Raw Ed25519 signature over the canonical receipt payload</li>
      <li><strong>signatureB64Url</strong> — Base64url encoding of the signature, used for transport</li>
    </ul>

    <h2 id="key-discovery">Key Discovery</h2>
    <p>Nodes publish their public keys at a well-known endpoint so verifiers can retrieve them independently. The <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">attestorKeyId</code> in the receipt identifies which key should be used for verification.</p>
    <CodeBlock
      code={`GET node.nexart.io/.well-known/nexart-node.json

{
  "nodeId": "nexart-node-primary",
  "activeKid": "key_01HXYZ...",
  "keys": [
    {
      "kid": "key_01HXYZ...",
      "algorithm": "Ed25519",
      "publicKey": "MCowBQYDK2VwAyEA..."
    }
  ]
}`}
      title="Node Key Discovery"
    />

    <h2 id="verification">Verifying a Receipt</h2>
    <ol>
      <li>Retrieve the node's public keys from <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">node.nexart.io/.well-known/nexart-node.json</code></li>
      <li>Select the key matching the receipt's <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">attestorKeyId</code></li>
      <li>Verify the Ed25519 signature over the canonical receipt payload</li>
      <li>Confirm the receipt's <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">certificateHash</code> matches the CER bundle</li>
    </ol>
    <p>Verification can also be performed through the public verifier at <a href="https://verify.nexart.io" target="_blank" rel="noopener noreferrer">verify.nexart.io</a>.</p>
  </>
);

export default SignedReceipts;
