import PageHeader from "@/components/docs/PageHeader";
import CodeBlock from "@/components/docs/CodeBlock";

const llmBlock = `# NexArt Signed Receipts
A signed receipt is the response you get after attestation. It contains:
- receipt_id: unique identifier
- cer_id: the associated CER
- signature: cryptographic proof from the attestation node
- timestamp: RFC 3339 timestamp
- node_id: which node signed it

Use receipts to prove an AI execution happened. Verify with: nexart.verify(receipt_id)`;

const SignedReceipts = () => (
  <>
    <PageHeader
      title="Signed Receipts"
      summary="The cryptographic proof you receive after each attestation."
      llmBlock={llmBlock}
    />
    <h2 id="what">What is a Signed Receipt?</h2>
    <p>When you submit an execution for attestation, NexArt returns a <strong>signed receipt</strong>. This receipt is your proof that the attestation node witnessed and recorded the execution.</p>
    <p>The signature is generated by the attestation node's private key. Anyone can verify it using the node's public key.</p>

    <h2 id="shape">Receipt Shape</h2>
    <CodeBlock
      code={`{
  "receipt_id": "rcpt_2k8m4x9n",
  "cer_id": "cer_8x7k2m4n9p",
  "signature": "0x3f2a8b1c4d5e6f...",
  "algorithm": "ECDSA-P256",
  "timestamp": "2026-03-06T12:00:00.000Z",
  "node_id": "nexart-node-us-east-1",
  "status": "confirmed"
}`}
      title="Receipt Response"
    />

    <h2 id="verification">Verifying a Receipt</h2>
    <p>Pass the receipt ID to the verify endpoint or SDK method. NexArt checks the signature, timestamp, and hash integrity.</p>
    <CodeBlock
      code={`const result = await nexart.verify("rcpt_2k8m4x9n");
// result.valid === true`}
      title="Verify"
    />
  </>
);

export default SignedReceipts;
