import PageHeader from "@/components/docs/PageHeader";
import CodeBlock from "@/components/docs/CodeBlock";

const llmBlock = `# NexArt Signed Receipts
A signed receipt is the canonical trust artifact in NexArt. It is the attestation proof returned by a node after it certifies a CER.

## What it proves
- The node witnessed the CER bundle
- The receipt binds the node's identity and timestamp to the CER's certificateHash
- The signature is Ed25519

## Canonical location
Attestation data lives at bundle.meta.attestation:
- meta.attestation.receipt — { certificateHash, timestamp, nodeId, kid }
- meta.attestation.signature — raw Ed25519 bytes
- meta.attestation.kid — signing key identifier

The API response may duplicate receipt and signatureB64Url at the top level for convenience.

## Trust hierarchy
1. Signed receipt (cer.ai.execution.v1 with attestation) — full attestation, fully verifiable
2. hash-only-timestamp — only certificateHash is signed, no snapshot attestation
3. legacy — older records, may lack attestation data

## Verification
1. Fetch node keys from node.nexart.io/.well-known/nexart-node.json
2. Select the key matching kid
3. Verify Ed25519 signature over the canonical receipt payload
4. Confirm receipt's certificateHash matches the CER bundle

Or verify through verify.nexart.io.

## Key discovery
node.nexart.io/.well-known/nexart-node.json
Fields: nodeId, activeKid, keys[] (kid, algorithm, publicKey)`;

const SignedReceipts = () => (
  <>
    <PageHeader
      title="Signed Receipts"
      summary="The canonical trust artifact returned by a node after it certifies a CER."
      llmBlock={llmBlock}
    />

    <h2 id="what">What is a Signed Receipt?</h2>
    <p>A signed receipt is the attestation proof returned by a NexArt node after it certifies a CER bundle. It is the canonical trust artifact in the NexArt protocol.</p>
    <p>The receipt binds three things together:</p>
    <ul>
      <li>The CER's <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">certificateHash</code></li>
      <li>The node's identity</li>
      <li>A timestamp</li>
    </ul>
    <p>The Ed25519 signature proves the node witnessed the record at that point in time. The node does not store or own the execution data.</p>

    <h2 id="canonical-location">Canonical Location</h2>
    <p>In a certified CER bundle, attestation data lives under <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">meta.attestation</code>:</p>
    <ul>
      <li><strong>meta.attestation.receipt</strong> — the canonical payload that was signed</li>
      <li><strong>meta.attestation.signature</strong> — raw Ed25519 signature</li>
      <li><strong>meta.attestation.kid</strong> — the signing key identifier</li>
    </ul>
    <p>The API response from <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">POST /v1/cer/ai/certify</code> duplicates the receipt and signature at the top level for convenience, but the CER bundle is the canonical source.</p>

    <h2 id="trust-hierarchy">Trust Hierarchy</h2>
    <p>Not all CERs have the same level of attestation. Signed receipts represent the strongest trust level:</p>
    <ol>
      <li><strong>Signed receipt</strong> — full node attestation. The entire CER bundle is witnessed and signed. This is the canonical trust model and the default when you use <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">POST /v1/cer/ai/certify</code>.</li>
      <li><strong>Hash-only timestamp</strong> — only the <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">certificateHash</code> is signed. The node attests the hash exists at a point in time but does not witness the full snapshot. Used when full attestation is not possible.</li>
      <li><strong>Legacy</strong> — older records that may lack attestation data entirely. Verification coverage is limited.</li>
    </ol>
    <p>For most integrations, signed receipts are what you want. They are the default output of the certify endpoint.</p>

    <h2 id="shape">Receipt Structure</h2>
    <p>The <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">receipt</code> object is the canonical payload that gets signed. Verification is always performed against this payload.</p>
    <CodeBlock
      code={`// Inside the CER bundle at meta.attestation:
{
  "receipt": {
    "certificateHash": "sha256:9e8d7c6b5a4f...",
    "timestamp": "2026-03-06T12:00:00.000Z",
    "nodeId": "nexart-node-primary",
    "kid": "key_01HXYZ..."
  },
  "signature": "<raw Ed25519 signature bytes>",
  "kid": "key_01HXYZ..."
}`}
      title="Attestation Data (meta.attestation)"
    />

    <h2 id="fields">Field Reference</h2>
    <ul>
      <li><strong>receipt</strong> — the canonical payload signed by the node.</li>
      <li><strong>certificateHash</strong> — SHA-256 hash of the CER bundle being attested.</li>
      <li><strong>timestamp</strong> — attestation time generated by the node (ISO 8601).</li>
      <li><strong>nodeId</strong> — identifies which node produced the receipt.</li>
      <li><strong>kid</strong> — the signing key identifier. Matches a key published at the node's well-known endpoint.</li>
      <li><strong>signature</strong> — raw Ed25519 signature over the canonical receipt payload.</li>
    </ul>
    <p>The API response also includes <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">signatureB64Url</code> (base64url encoding) for transport convenience.</p>

    <h2 id="verification-url">Verification URLs</h2>
    <p>When you certify a record via the API, the response includes a <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">verificationUrl</code>. This URL points to the public verifier where anyone can independently check the record:</p>
    <CodeBlock
      code={`// By execution ID
https://verify.nexart.io/e/exec_abc123

// By certificate hash
https://verify.nexart.io/c/sha256%3A7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069`}
      title="Verification URL Formats"
    />
    <p>The verification URL is safe to share. The public verifier shows only a redacted, public-safe representation of the record.</p>

    <h2 id="key-discovery">Key Discovery</h2>
    <p>Nodes publish their public keys at a well-known endpoint. The <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">kid</code> in the receipt tells you which key to use for verification.</p>
    <CodeBlock
      code={`GET node.nexart.io/.well-known/nexart-node.json

{
  "nodeId": "nexart-node-primary",
  "activeKid": "key_01HXYZ...",
  "keys": [
    {
      "kid": "key_01HXYZ...",
      "algorithm": "Ed25519",
      "publicKey": "MCowBQYDK2VwAyEA..."
    }
  ]
}`}
      title="Node Key Discovery"
    />

    <h2 id="verification">Verifying a Receipt</h2>
    <ol>
      <li>Retrieve the node's public keys from <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">node.nexart.io/.well-known/nexart-node.json</code></li>
      <li>Select the key matching the receipt's <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">kid</code></li>
      <li>Verify the Ed25519 signature over the canonical receipt payload</li>
      <li>Confirm the receipt's <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">certificateHash</code> matches the CER bundle</li>
    </ol>
    <p>This process requires no API access to NexArt. You only need the CER bundle and the node's published public key.</p>
    <p>You can also verify through the public verifier at <a href="https://verify.nexart.io" target="_blank" rel="noopener noreferrer">verify.nexart.io</a>.</p>
  </>
);

export default SignedReceipts;
