// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-docs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var DOCS_BASE = "https://docs.nexart.io";
async function fetchIndex() {
  const res = await fetch(`${DOCS_BASE}/llms.txt`);
  if (!res.ok) throw new Error(`Failed to load docs index: ${res.status}`);
  const text = await res.text();
  const entries = [];
  let section = "General";
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (line.startsWith("## ")) {
      section = line.slice(3).trim();
      continue;
    }
    const m = line.match(/^-\s+\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/);
    if (m) entries.push({ title: m[1], url: m[2], section });
  }
  return entries;
}
var list_docs_default = defineTool({
  name: "list_docs",
  title: "List NexArt Docs",
  description: "List all pages of the NexArt documentation (docs.nexart.io) grouped by section. Use this to discover what topics exist before fetching a specific page.",
  inputSchema: {
    section: z.string().optional().describe("Optional case-insensitive section filter, e.g. 'Verification', 'Integrations'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ section }) => {
    const entries = await fetchIndex();
    const filtered = section ? entries.filter((e) => e.section.toLowerCase().includes(section.toLowerCase())) : entries;
    const bySection = {};
    for (const e of filtered) {
      (bySection[e.section] ||= []).push({ title: e.title, url: e.url });
    }
    return {
      content: [{ type: "text", text: JSON.stringify(bySection, null, 2) }],
      structuredContent: { count: filtered.length, sections: bySection }
    };
  }
});

// src/lib/mcp/tools/search-docs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var DOCS_BASE2 = "https://docs.nexart.io";
var search_docs_default = defineTool2({
  name: "search_docs",
  title: "Search NexArt Docs",
  description: "Keyword search across NexArt documentation page titles and URLs (docs.nexart.io). Returns the best matching pages. Use fetch_doc to read a specific page.",
  inputSchema: {
    query: z2.string().min(1).describe("Keywords to search for, e.g. 'certificate hash verification'."),
    limit: z2.number().int().min(1).max(25).default(10).describe("Maximum number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const res = await fetch(`${DOCS_BASE2}/llms.txt`);
    if (!res.ok) throw new Error(`Failed to load docs index: ${res.status}`);
    const text = await res.text();
    const entries = [];
    let section = "General";
    const lines = text.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.startsWith("## ")) {
        section = line.slice(3).trim();
        continue;
      }
      const m = line.match(/^-\s+\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)(.*)$/);
      if (m) {
        const snippetLines = [m[3].trim()];
        for (let j = i + 1; j < lines.length && (lines[j].startsWith("  ") || lines[j].trim() === ""); j++) {
          snippetLines.push(lines[j].trim());
        }
        entries.push({
          title: m[1],
          url: m[2],
          section,
          snippet: snippetLines.join(" ").trim()
        });
      }
    }
    const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    const scored = entries.map((e) => {
      const hay = `${e.title} ${e.url} ${e.section} ${e.snippet}`.toLowerCase();
      let score = 0;
      for (const t of terms) {
        if (e.title.toLowerCase().includes(t)) score += 5;
        if (hay.includes(t)) score += 1;
      }
      return { ...e, score };
    }).filter((e) => e.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map(({ score: _s, ...rest }) => rest);
    return {
      content: [
        {
          type: "text",
          text: scored.length ? JSON.stringify(scored, null, 2) : `No results for "${query}".`
        }
      ],
      structuredContent: { count: scored.length, results: scored }
    };
  }
});

// src/lib/mcp/tools/fetch-doc.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var DOCS_HOST = "docs.nexart.io";
function normalizeUrl(input) {
  if (input.startsWith("http://") || input.startsWith("https://")) return input;
  if (input.startsWith("/")) return `https://${DOCS_HOST}${input}`;
  return `https://${DOCS_HOST}/${input.replace(/^\/+/, "")}`;
}
function stripHtml(html) {
  const mainMatch = html.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
  const scope = mainMatch ? mainMatch[1] : html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)?.[1] ?? html;
  return scope.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<nav[\s\S]*?<\/nav>/gi, "").replace(/<footer[\s\S]*?<\/footer>/gi, "").replace(/<br\s*\/?>/gi, "\n").replace(/<\/(p|div|h[1-6]|li|section|article)>/gi, "\n").replace(/<li[^>]*>/gi, "- ").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\n{3,}/g, "\n\n").replace(/[ \t]+\n/g, "\n").trim();
}
var fetch_doc_default = defineTool3({
  name: "fetch_doc",
  title: "Fetch NexArt Doc Page",
  description: "Fetch the readable text of a NexArt documentation page. Accepts a full https://docs.nexart.io/... URL or a path like /docs/verification.",
  inputSchema: {
    url: z3.string().min(1).describe("Doc page URL or path, e.g. '/docs/verification'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    const target = normalizeUrl(url);
    if (!/^https:\/\/(www\.)?docs\.nexart\.io\//.test(target)) {
      return {
        content: [{ type: "text", text: `Refusing to fetch non-docs URL: ${target}` }],
        isError: true
      };
    }
    const res = await fetch(target, { headers: { Accept: "text/html" } });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch ${target}: ${res.status}` }],
        isError: true
      };
    }
    const html = await res.text();
    const text = stripHtml(html);
    const trimmed = text.length > 2e4 ? text.slice(0, 2e4) + "\n\n\u2026 [truncated]" : text;
    return {
      content: [{ type: "text", text: `# ${target}

${trimmed}` }],
      structuredContent: { url: target, length: text.length, text: trimmed }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nexart-docs-mcp",
  title: "NexArt Docs",
  version: "0.1.0",
  instructions: "Tools for exploring the NexArt documentation at docs.nexart.io. Use `search_docs` to find pages by keyword, `list_docs` to browse by section, and `fetch_doc` to read the full text of a specific page.",
  tools: [list_docs_default, search_docs_default, fetch_doc_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
